config/routes.rb
Rails.application.routes.draw do

  resources :users

  post 'user_token' => 'user_token#create'
  post 'super_user_token' => 'super_user_token#create'
  post 'admin_token' => 'admin_token#create'

  root to: 'pages#home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :spots do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :features, presence: true
  validates :spot_type, presence: true
  validates :description, presence: true
  validates :lat, presence: true
  validates :lon, presence: true
  validates_numericality_of :lat
  validates_numericality_of :lon
end

app/controllers/spots_controller.rb
require 'pry'

class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :show, :edit, :create, :update, :destroy, :new]

  # GET /spots
  # GET /spots.json
  def index
    # Idea: for the list of spots to display: find the 10 closest to your location
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @response = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?lat=#{@spot.lat}&lon=#{@spot.lon}&appid=#{Rails.application.credentials.weather_api_key}")
    @reviews = @spot.reviews
    heat_img = 'https://www.iconsdb.com/icons/preview/red/handcuffs-xxl.png'
    rating_img = 'https://lh3.googleusercontent.com/proxy/9-wxcpu48pZbd4f6LMK67Qf7ZSCvM_uIPXR2FoW6HW32wsT0F1R0OVBxax8FmjxNUc_mgH4e4gtAHBMps1cpCXC98ItWjzAArgTzjC5T4Mi_73xCZJbAuyeB4XhD_r__T1gy3vNfDhrbBKiD0Kg'
    @rating_array = []
    @heat_array = []
    @avg_rating = 0
    heat_levels = []
    @reviews.each do |review|
      @avg_rating += review.rating
      heat_levels.push(review.heat_lvl)
    end
    if @reviews.length > 0
      @avg_rating = @avg_rating / @reviews.length
      heat_levels.sort!
      len = heat_levels.length
      @med_heat = (heat_levels[(len - 1) / 2] + heat_levels[len / 2]) / 2.0

      (@med_heat.round).times do |index|
        @heat_array.push(heat_img)
      end

      (@avg_rating.round).times do |index|
        @rating_array.push(rating_img)
      end
    end
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)
    @spots = Spot.all
    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|

      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
        if params[:spot][:photos]
          @spot.photos.attach(params[:spot][:photos])
        end
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_spot
    @spot = Spot.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def spot_params
    params.require(:spot).permit(:name, :lat, :lon, :spot_type, :features, :description, photo: [])
  end


end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
  document.addEventListener("DOMContentLoaded", initMap2);
</script>
<% end %>


<%= form_with(model: spot, local: true) do |form| %>
<% if spot.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

  <ul>
    <% spot.errors.full_messages.each do |message| %>

    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <div class="basic_map" id="map2"></div>
</p>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :lat %>
  <%= form.text_field :lat %>
</div>

<div class="field">
  <%= form.label :lon %>
  <%= form.text_field :lon %>
</div>

<div class="field">
  <%= form.label :spot_type %>
  <%= form.text_field :spot_type %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="field">
  <%= form.label :features %>
  <%= form.text_field :features %>
</div>

<div class="field">
  <%= form.label :photos %>
  <%= form.file_field :photos %>
</div>



<div class="actions">
  <button class="sButton" type="submit" name="button">Create Spot!</button>
</div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>

    <script>
    var spots_list_raw = '<%= @spots.to_json.html_safe %>';
    document.addEventListener("DOMContentLoaded", function(){
        initBigMap()
    });
    </script>
<% end %>

<p id="notice"><%= notice %></p>

<h1 class="subTitle">SK8 SpotZ</h1>
<p>
  <div class="basic_map" id="bigMap"></div>
</p>


<table>
  <thead>
    <tr>
      <th class="spotHead">Name</th>
      <th class="spotHead">Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td class="dTable"><%= spot.name %></td>
        <td class="dTable"><%= spot.spot_type %></td>
        <td class="dTable"><%= link_to 'Show', spot %></td>
        <td class="dTable"><%= link_to 'Edit', edit_spot_path(spot) %></td>
        <td class="dTable"><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
  document.addEventListener("DOMContentLoaded", function(){

    initMap(<%=@spot.lat%>, <%=@spot.lon%>)
  });
</script>
<% end %>

<p id="notice"><%= notice %></p>
<h1><%= @spot.name %></h1>
<strong>Current Weather Conditions:</strong>
<%= @response["weather"][0]["description"].titleize %>,
<% temp_c = (((@response["main"]["temp"] - 273.15) * (9/5)) + 32) %>
<%= temp_c.round %> °F


<div class="photo_box">
<% if @spot.photos.attached? %>
<% @spot.photos.each do |photo| %>
    <span><%= image_tag(photo, :class => "photo") %></span>
  <% end %>
  <% else %>
  No photos for this spot.
<% end %>
</div>


<div class="review_box">
  <% if @reviews.any? %>
  <h3>Reviews</h3>
  <ul>
    <% @reviews.each do |review| %>
    <li>
      <a href="/spots/<%= @spot.id %>/reviews/<%= review.id %>"><%= review.title %></a>
      <h5>Rating: <%= review.rating %></h5>
      <h5>Heat level: <%= review.heat_lvl %></h5>
      <p><%= review.content %></p>
    </li>
    <% end %>
  </ul>
  <% else %>
  <h3>No reviews!</h3>
  <% end %>
</div>


<p>
  <div class="basic_map" id="map"></div>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @spot.lat %> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
  <strong>Longitude:</strong>
  <%= @spot.lon %>
</p>
<p>
  Average rating:
</p>
<p>
  <% @rating_array.each do |image| %>
  <span><img class="skate_icon" src="<%=image%>" alt="star"></span>
  <% end %>
</p>
<br>
<p>
  Cop watch:
</p>
<p>
  <% @heat_array.each do |image| %>
  <span><img class="skate_icon" src="<%=image%>" alt="star"></span>
  <% end %>
</p>



<p>
  <strong>Spot Type</strong>
  <%= @spot.spot_type %>
</p>
<p>
  <strong>Features</strong>
  <%= @spot.features %>
</p>
<p>
  <strong>Description</strong>
  <%= @spot.description %>
</p>



<p>
  <%= link_to 'Edit', edit_spot_path(@spot) %>
  <%= link_to 'Add review', new_spot_review_path(@spot) %>
  <%= link_to 'Back', spots_path %>