config/routes.rb
Rails.application.routes.draw do

  resources :users

  post 'user_token' => 'user_token#create'
  post 'super_user_token' => 'super_user_token#create'
  post 'admin_token' => 'admin_token#create'

  root to: 'pages#home'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :spots do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
require 'pry'

class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :get_user, only: [:create, :new, :edit, :update]
  before_action :find_spot
  # GET /reviews
  # GET /reviews.json
  # def index
  #   @reviews = Review.all
  # end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @spot.reviews.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to "/spots/#{@review.spot_id}", notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to "/spots/#{@review.spot_id}/reviews/#{@review.id}", notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    id = @review.spot_id
    @review.destroy
    respond_to do |format|
      format.html { redirect_to "/spots/#{id}", notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def find_spot
      @spot = Spot.find(params[:spot_id])
    end

    def get_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      # params.fetch(:review, {})
      params.require(:review).permit(:title, :content, :rating, :heat_lvl, :user_id, :spot_id)
    end
end

# avg = 0
# heat_array = []
# for each review
#   heat_array.push(review.heat_level)
# end
#
# heat_array.each do |number|
#   avg += number
# end
#
# avg = avg/heat_array.len

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for [@spot, @review] do |f| %>
<%= f.hidden_field :user_id, :value => @user.id %>
<br>
<%= f.label "title" %>
<%= f.text_field :title %>
<br>
<%= f.label "Content" %>
<%= f.text_area :content %>
<br>
<%= f.label "Rating" %>
<%= f.text_field :rating %>
<br>
<%= f.label "Heat Level" %>
<%= f.text_field :heat_lvl %>
<hr>
<p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', "/spots/#{@spot.id}/reviews/#{@review.id}" %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', "/spots/#{@spot.id}" %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @review.title %></h2>
<p><%= @review.content %></p>
<h3>Rating: <%= @review.rating %></h3>
<h3>Heat: <%= @review.heat_lvl %></h3>

<%= link_to 'Back', "/spots/#{@spot.id}" %> |
<%= link_to 'Edit', edit_spot_review_path %> 

<p>
  <%=
  link_to "Delete review", spot_review_path(@spot, @review),
  :data => {:confirm => "Are you sure?",
  :method => "delete"}
  %>
</p>